name: Go
on: [push]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.13
        uses: actions/setup-go@v1
        with:
          go-version: "1.13"

      - name: Check out code into the Go module directory
        uses: actions/checkout@master

      - uses: actions/cache@v1
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Install tools
        run: |
          go get -u golang.org/x/lint/golint

      - name: Lint
        run: make lint

      - name: Test
        run: make test

      - uses: codecov/codecov-action@v1

      - name: Build
        run: make build
